### ISSUE TITLE
Aucun fichier ne se télécharge

### ISSUE THREAD

**Issue by vinyll** [oeil/deplacement-covid-19#2]
L'attestation se télécharge bien depuis l'application officielle, mais pas depuis oeil.github.io.
Même souci en local depuis le master.

La page bleue de generate.html s'affiche normalement et aucune fenetre de téléchargement ni de fichier dans le dossier habituel.
Tester sur Firefox 82, Brave 1.16 (Chromium 86) et Safari.

**Comment by oeil** [comment]
Merci - le souci est fixé.
